### ISSUE TITLE
v9.4.x Keepalive feature breaks build on OpenBSD 7.5

### ISSUE THREAD

**Issue by Sir-Photch** [erebe/wstunnel#270]
**To Reproduce**
Clone repo on OpenBSD 7.5 and build it with rust 1.76 via `cargo r`

```ksh
myhostname$ cargo r
   Compiling wstunnel v9.4.0 (/home/chris/wstunnel)
warning: unused variable: `ip_transparent`
   --> src/tcp.rs:185:43
    |
185 | ...er(bind: SocketAddr, ip_transparent: bool) -> Result<TcpListenerStre...
    |                         ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_ip_transparent`
    |
    = note: `#[warn(unused_variables)]` on by default

error[E0599]: no method named `with_interval` found for struct `TcpKeepalive` in the current scope
  --> src/tcp.rs:29:10
   |
27 |       let tcp_keepalive = TcpKeepalive::new()
   |  _________________________-
28 | |         .with_time(Duration::from_secs(60))
29 | |         .with_interval(Duration::from_secs(10))
   | |         -^^^^^^^^^^^^^ method not found in `TcpKeepalive`
   | |_________|
   |

For more information about this error, try `rustc --explain E0599`.
warning: `wstunnel` (bin "wstunnel") generated 1 warning
error: could not compile `wstunnel` (bin "wstunnel") due to 1 previous error; 1 warning emitted
```

v9.3.0 builds fine.

**Comment by erebe** [comment]
I pushed a fix on main, would you mind trying with the head of main and let me know ?

**Comment by Sir-Photch** [comment]
Yep, builds!
